### ISSUE TITLE
Auto-update doesn't work reliably

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/forum#1663]
On my Win7 machine, the auto-update only works if I restart the computer.  Today, it even took two restarts to work.

I tested this today through two updates:
- SN had been at v3.14.1 for about a month without showing the blue "New update" notice, but recognized that a new update (v3.22.11) was available.  Restarting the app did not help (checked that process had stopped).
- Restarted the machine and upon launching SN it showed the blue "New update" notice, then I was able to close and successfully update the app to v3.22.11 (the latest available on that archived repo)
- After restarting the app, it again refused to show the "New update" notice but it did recognize that a new update (v3.23.61) was available.  Restarting the app did not help (checked that process had stopped).
- After restarting the computer, it still surprisingly would not show the "New update" notice.
- But after restarting the computer a second time and launching the SN app, it showed that blue notice and I was able to successfully update the app to v3.23.61 (the latest as of today).

So for anyone experiencing issues with the auto-update, at least on Windows, **_try restarting your PC--twice even--and see if the auto-update works then_**.

And FYI, in my tests, **_the blue "New update" notice appears very quickly_** (when it worked) upon launching the app, between 20 seconds and 2 minutes.  So for users that are waiting hours or days expecting it to appear: don't.

Similar:
https://github.com/standardnotes/desktop/issues/880
https://www.reddit.com/r/StandardNotes/comments/v7jhe6/auto_update_functionality/
https://github.com/standardnotes/forum/issues/1299
https://github.com/standardnotes/forum/issues/1714
https://github.com/standardnotes/forum/issues/1739

**Comment by fawaf** [comment]
very much +1. the auto update is pretty terrible. why is there not a manual "update now" button of sorts?

**Comment by effieeee** [comment]
Will continue tracking here: https://github.com/standardnotes/forum/issues/1714

**Comment by selan321** [comment]
Hi, I didn't see any error messages attached to this ticket, and/or the others referenced, so here's the ones I got. Hopping it can help. (mismatch in the filename downloaded vs. the chmod command...?)

```
11:45:13.935 › Checking for update
11:45:14.539 › Found version 3.23.273 (url: standard-notes-3.23.273-linux-x86_64.AppImage)
11:45:14.554 › Downloading update from standard-notes-3.23.273-linux-x86_64.AppImage

11:45:15.319 › Full: 121,236.11 KB, To download: 35,098.29 KB (29%)
11:45:15.337 › Differential download: https://github.com/standardnotes/app/releases/download/@standardnotes/desktop@3.23.273/standard-notes-3.23.273-linux-x86_64.AppImage
11:45:15.383 › File has 1708 changed blocks

11:45:15.396 › Full: 121,236.11 KB, To download: 35,098.29 KB (29%)
11:45:15.410 › Differential download: https://github.com/standardnotes/app/releases/download/@standardnotes/desktop@3.23.273/standard-notes-3.23.273-linux-x86_64.AppImage
11:45:15.417 › Redirect to https://objects.githubusercontent.com/github-production-release-asset-2e65be/75675698/22ea1031-8b10-4896-b4d7-e1f552a9b768
11:45:15.794 › Redirect to https://objects.githubusercontent.com/github-production-release-asset-2e65be/75675698/22ea1031-8b10-4896-b4d7-e1f552a9b768

11:45:51.955 › New version 3.23.273 has been downloaded to /home/user/.cache/@standardnotesinner-desktop-updater/pending/standard-notes-3.23.273-linux-x86_64.AppImage

11:45:53.738 › Error: Error: ENOENT: no such file or directory, chmod '/home/user/.cache/@standardnotesinner-desktop-updater/pending/temp-standard-notes-3.23.273-linux-x86_64.AppImage'
updateManager: [Error: ENOENT: no such file or directory, chmod '/home/user/.cache/@standardnotesinner-desktop-updater/pending/temp-standard-notes-3.23.273-linux-x86_64.AppImage'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path: '/home/user/.cache/@standardnotesinner-desktop-updater/pending/temp-standard-notes-3.23.273-linux-x86_64.AppImage'
} Error: ENOENT: no such file or directory, chmod '/home/user/.cache/@standardnotesinner-desktop-updater/pending/temp-standard-notes-3.23.273-linux-x86_64.AppImage'
(node:246954) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chmod '/home/user/.cache/@standardnotesinner-desktop-updater/pending/temp-standard-notes-3.23.273-linux-x86_64.AppImage'
(Use `standard-notes --trace-warnings ...` to show where the warning was created)
(node:246954) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

11:46:32.470 › Install on explicit quitAndInstall
11:46:32.474 › Error: Error: No valid update available, can't quit and install
    at d.install (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:213747)
    at d.quitAndInstall (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:213176)
    at Timeout._onTimeout (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:115873)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
updateManager: Error: No valid update available, can't quit and install
    at d.install (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:213747)
    at d.quitAndInstall (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:213176)
    at Timeout._onTimeout (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:115873)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) Error: No valid update available, can't quit and install
    at d.install (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:213747)
    at d.quitAndInstall (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:213176)
    at Timeout._onTimeout (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:115873)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
11:46:32.497 › Auto install update on quit
11:46:32.499 › Error: Error: No valid update available, can't quit and install
    at d.install (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:213747)
    at /tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:214389
    at App.<anonymous> (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:218537)
    at Object.onceWrapper (node:events:510:26)
    at App.emit (node:events:402:35)
    at App.<anonymous> (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:143893)
    at App.emit (node:events:402:35)
updateManager: Error: No valid update available, can't quit and install
    at d.install (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:213747)
    at /tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:214389
    at App.<anonymous> (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:218537)
    at Object.onceWrapper (node:events:510:26)
    at App.emit (node:events:402:35)
    at App.<anonymous> (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:143893)
    at App.emit (node:events:402:35) Error: No valid update available, can't quit and install
    at d.install (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:213747)
    at /tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:214389
    at App.<anonymous> (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:218537)
    at Object.onceWrapper (node:events:510:26)
    at App.emit (node:events:402:35)
    at App.<anonymous> (/tmp/.mount_standaNBsKPI/resources/app.asar/dist/index.js:2:143893)
    at App.emit (node:events:402:35)
```

**Comment by fawaf** [comment]
@selan321 ohh how did you get the logs? didn't know one could get that.

**Comment by selan321** [comment]
> @selan321 ohh how did you get the logs? didn't know one could get that.

Launch it from a terminal. In my case, using linux, 
```
$ chmod +x standard-notes-3.23.273-linux-x86_64.AppImage
$ ./standard-notes-3.23.273-linux-x86_64.AppImage
```

**Comment by ElCoyote27** [comment]
I'm also seeing that trying to update from 3.173.4 to 3.173.20:

```updateManager: Error: No valid update available, can't quit and install
    at d.install (/tmp/.mount_standaVfbfMC/resources/app.asar/dist/index.js:2:388074)
    at /tmp/.mount_standaVfbfMC/resources/app.asar/dist/index.js:2:388716
    at App.<anonymous> (/tmp/.mount_standaVfbfMC/resources/app.asar/dist/index.js:2:392863)
    at Object.onceWrapper (node:events:628:26)
    at App.emit (node:events:525:35)
    at App.<anonymous> (/tmp/.mount_standaVfbfMC/resources/app.asar/dist/index.js:2:281801)
    at App.emit (node:events:525:35) Error: No valid update available, can't quit and install
    at d.install (/tmp/.mount_standaVfbfMC/resources/app.asar/dist/index.js:2:388074)
    at /tmp/.mount_standaVfbfMC/resources/app.asar/dist/index.js:2:388716
    at App.<anonymous> (/tmp/.mount_standaVfbfMC/resources/app.asar/dist/index.js:2:392863)
    at Object.onceWrapper (node:events:628:26)
    at App.emit (node:events:525:35)
    at App.<anonymous> (/tmp/.mount_standaVfbfMC/resources/app.asar/dist/index.js:2:281801)
    at App.emit (node:events:525:35)
```
