### ISSUE TITLE
Android app crashes when loading any non-plain text note

### ISSUE THREAD

**Issue by zeitrechnen** [standardnotes/forum#2202]
**Describe the bug**
After to update to Standard Notes 3.42.5 the app crashes whenever I click on a non plain text note. 

**To Reproduce**
1. Go to notes overview
2. Click on on a note that is not a plain text note
3. Note appears for a very short moment
4. App crashes

**Expected behavior**
Note opens without crashing.

**Log**
```
type: crash
osVersion: google/bluejay/bluejay:13/TP1A.221005.003/2022101500:user/release-keys
package: com.standardnotes:3000553
process: com.standardnotes

com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'source' of undefined, js engine: hermes, stack:
anonymous@1450:2808
anonymous@974:3410
o@55:150
h@55:293
g@55:347
S@55:658
Ee@55:13161
W@55:5356
anonymous@55:13509
Te@55:94060
Pe@55:12971
Ne@55:13348
receiveEvent@55:13764
value@36:3556
anonymous@36:673
value@36:2503
value@36:645

    at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:72)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
    at android.os.Handler.handleCallback(Handler.java:942)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
    at android.os.Looper.loopOnce(Looper.java:201)
    at android.os.Looper.loop(Looper.java:288)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
    at java.lang.Thread.run(Thread.java:1012)
```

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6a
 - OS: GrapheneOS (Android 13)
 - Security Patch: October 5

**Additional context**
I also wonder why there is a facebook module ...

**Comment by ataraxia937** [comment]
Here also. I'm running 3.42.5 from F-droid on Graphene OS. It only crashes with the "New Mobile Experience Preview" disabled. If I do opt in to the new UI, it doesn't crash.

**Comment by mixint7** [comment]
The same happens for me.

Standard Notes version: 3.41.10
Device: Oppo Reno3 Pro
OS: ColorOS (Android 12)
Security Patch: 2022-09-05

The workaround with switching to the "New Mobile Experience Preview" works perfectly though.

**Comment by effieeee** [comment]
Hi all, yes, it's recommended that everyone switch to the new mobile experience, as this is also set to replace the old UI on both iOS and Android eventually 🙏
