### ISSUE TITLE
broken standard-notes snap

### ISSUE THREAD

**Issue by keshavbhatt** [standardnotes/forum#3058]
**Describe the bug**
**Install:**
`snap install standard-notes`

**Run:**
`standard-notes`

```
Set user data dir to /home/commander/snap/standard-notes/common
Migration: moving /home/commander/snap/standard-notes/684/.config/Standard Notes/logs to /home/commander/snap/standard-notes/common
Migration: error occured while moving /home/commander/snap/standard-notes/684/.config/Standard Notes/logs to /home/commander/snap/standard-notes/common: dest already exists.
Migration: finished moving contents to /home/commander/snap/standard-notes/common.
Error reading store file Error: ENOENT: no such file or directory, open '/home/commander/snap/standard-notes/common/user-preferences.json'
    at Object.openSync (node:fs:594:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
    at Object.readFileSync (node:fs:462:35)
    at t.readFileSync (node:electron/js2c/asar_bundle:2:9165)
    at q (/snap/standard-notes/684/resources/app.asar/dist/index.js:2:121907)
    at new V (/snap/standard-notes/684/resources/app.asar/dist/index.js:2:122380)
    at /snap/standard-notes/684/resources/app.asar/dist/index.js:2:248183
    at 7696 (/snap/standard-notes/684/resources/app.asar/dist/index.js:2:248712)
    at n (/snap/standard-notes/684/resources/app.asar/dist/index.js:2:766434)
    at /snap/standard-notes/684/resources/app.asar/dist/index.js:2:766945 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/commander/snap/standard-notes/common/user-preferences.json'
}
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at /snap/standard-notes/684/resources/app.asar/dist/index.js:2:248221
    at 7696 (/snap/standard-notes/684/resources/app.asar/dist/index.js:2:248712)
    at n (/snap/standard-notes/684/resources/app.asar/dist/index.js:2:766434)
    at /snap/standard-notes/684/resources/app.asar/dist/index.js:2:766945
    at Object.<anonymous> (/snap/standard-notes/684/resources/app.asar/dist/index.js:2:766958)
    at Module._compile (node:internal/modules/cjs/loader:1141:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)

(standard-notes:638995): GdkPixbuf-WARNING **: 12:25:38.105: Cannot open pixbuf loader module file '/home/commander/snap/standard-notes/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/commander/snap/standard-notes/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.

(standard-notes:638995): Gtk-WARNING **: 12:25:38.112: Theme parsing error: gtk-dark.css:1413:23: 'font-feature-settings' is not a valid property name

(standard-notes:638995): Gtk-WARNING **: 12:25:38.118: Theme parsing error: gtk-dark.css:3286:25: 'font-feature-settings' is not a valid property name

(standard-notes:638995): Gtk-WARNING **: 12:25:38.119: Theme parsing error: gtk-dark.css:3748:23: 'font-feature-settings' is not a valid property name
Gtk-Message: 12:25:38.174: Failed to load module "colorreload-gtk-module"
Gtk-Message: 12:25:38.175: Failed to load module "window-decorations-gtk-module"
WARNING: Kernel has no file descriptor comparison support: Operation not permitted

```

**To Reproduce**
1. Install
`snap install standard-notes`

2. Run
`standard-notes`

**Expected behavior**
App should launch properly

**Desktop (please complete the following information):**
 - OS: EndeavourOS Linux

**Additional info:**

`snap info standard-notes`

```
name:      standard-notes
summary:   Standard Notes
publisher: Standard Notes (standardnotes**)
store-url: https://snapcraft.io/standard-notes
contact:   help@standardnotes.com
license:   unset
description: |
  An end-to-end encrypted notes app for digitalists and professionals.
commands:
  - standard-notes
snap-id:      54zJyS09HO95Dwafu93mvAiQzFz3FAtY
tracking:     latest/stable
refresh-date: today at 12:11 IST
channels:
  latest/stable:    3.159.9 2023-05-12 (684) 100MB -
  latest/candidate: 3.159.9 2023-05-12 (684) 100MB -
  latest/beta:      3.159.9 2023-05-12 (684) 100MB -
  latest/edge:      3.159.9 2023-05-12 (684) 100MB -
installed:          3.159.9            (684) 100MB -

```

**Comment by monoprix** [comment]
I have the exact same problem on fresh installs of Linux Mint 21.1 and Pop_OS! 22.04 LTS on two different computers.

**Comment by E-Bop** [comment]
I also have this issue. OS Ubuntu 23.04

**Comment by jspaetzel** [comment]
i also have this on a new install of Ubuntu 23.04. The AppImage works ok only the Snap is broken

**Comment by amanharwara** [comment]
Should be fixed with [v3.169.26](https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.169.26)
