### ISSUE TITLE
Blank Window

### ISSUE THREAD

**Issue by attilatob** [standardnotes/forum#3363]
I was using Standard Notes for month without any issue, I have a Productivity Plan
but today it is showing only a blank window, the menu system is working, but nothing else, no log in request, no notes either, even after uninstalling and reinstalling it

**Comment by widavies** [comment]
Same here

**Comment by widavies** [comment]
After latest update, window goes white:

![image](https://github.com/standardnotes/forum/assets/11671115/dcf419db-a575-4656-86e0-27d0d304b134)

**Comment by attilatob** [comment]
Glad, I'm not alone ... :-(

**Comment by widavies** [comment]
For me, installing this version: https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.181.29 works, `3.181.30` and `3.181.31` both don't work

**Comment by attilatob** [comment]
works for me too ... thank!

**Comment by rddphoto** [comment]
Newbie here, not capable of coding, nor willing to. Program was working earlier this morning, then the window went blank.

I had upgraded to 3.181.31 a couple of days ago and all was well, then this.

How do I do as widavies has suggested above, and downgrade to version 3.181.29? Step-by-simple-step instructions would be much appreciated. Thanks in advance!

**Comment by kleters** [comment]
Same here. I was using 3.181.25 and upgrading to 3.181.31 did not help. Neither did reloading or clearing cache and reloading. Console says:

![image](https://github.com/standardnotes/forum/assets/151785072/5decac48-fe3b-4af8-aa3b-f2e99cd5e602)

Error: EncryptedPayload constructor versionResult is failed
    at new s (app.js:2:1301183)
    at app.js:2:1737479
    at Array.map (<anonymous>)
    at f.<anonymous> (app.js:2:1737471)
    at Generator.next (<anonymous>)
    at s (app.js:2:1734628)

I am using **standard-notes-3.181.31-linux-x86_64.AppImage**.

**Comment by ilyak83** [comment]
Same here

![image](https://github.com/standardnotes/forum/assets/37582972/0ace0865-4933-4af0-8acb-dee06f040b53)

**Comment by rddphoto** [comment]
> For me, installing this version: https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.181.29 works, `3.181.30` and `3.181.31` both don't work

**Comment by rddphoto** [comment]
How do you dowgrade an installed version from .31 to .29? Sorry, I'm a newbie with no desire to deal with coding... :-P

**Comment by rddphoto** [comment]
> For me, installing this version: https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.181.29 works, `3.181.30` and `3.181.31` both don't work

How do you dowgrade an installed version from .31 to .29? Sorry, I'm a newbie with no desire to deal with coding... :-P

**Comment by rouspreda** [comment]
Same issue happened to me after upgrading to `standard-notes-3.181.31-win-x64.exe` on Windows 10 x64.

No issues using the web app.

Edit 2023-11-23: Per @VFlame44 `standard-notes-3.181.32-win-x64.exe` fixes the white screen issue for me as well.

![2023-11-22_blank_window_console_errors](https://github.com/standardnotes/forum/assets/115921344/335424ef-8803-4d81-85a0-eba57407ff3f)

**Comment by cam-coding** [comment]
+1 For this issue

> > For me, installing this version: https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.181.29 works, `3.181.30` and `3.181.31` both don't work
> 
> How do you dowgrade an installed version from .31 to .29? Sorry, I'm a newbie with no desire to deal with coding... :-P

If you go to that page and scroll down, you want to select one of the .exe files from the list based on your OS. So in my case I chose "standard-notes-3.181.29-win-x64.exe" and clicked on it which started a download. Then I ran the exe which removed the current version of Standard Notes and installed 3.181.29.

Also you should go into the top left menu, hover over "Updates" and then disable automatic updates (at least until this is fixed!)

**Comment by rddphoto** [comment]
> +1 For this issue
> 
> > > For me, installing this version: https://github.com/standardnotes/app/releases/tag/%40standardnotes%2Fdesktop%403.181.29 works, `3.181.30` and `3.181.31` both don't work
> > 
> > 
> > How do you dowgrade an installed version from .31 to .29? Sorry, I'm a newbie with no desire to deal with coding... :-P
> 
> If you go to that page and scroll down, you want to select one of the .exe files from the list based on your OS. So in my case I chose "standard-notes-3.181.29-win-x64.exe" and clicked on it which started a download. Then I ran the exe which removed the current version of Standard Notes and installed 3.181.29.
> 
> Also you should go into the top left menu, hover over "Updates" and then disable automatic updates (at least until this is fixed!)

Thanks for the tip! However, you said that running the exe "removes the current version..." Will doing so preserve my data? I certainly hope so!!! :-O :-O :-O

**Comment by kleters** [comment]
Blank window in `standard-notes-3.181.31-linux-x86_64.AppImage` could be fixed by just deleting all the files you can find under **Help**  >  **Open Data Directory**   [eventually you need to follow the complete [uninstall instructions](https://standardnotes.com/help/72/how-do-i-uninstall-standard-notes)]

After that standard notes was working again.

I also tested with 3.181.29. Guess that fixes it for all versions.

**Comment by VFlame44** [comment]
Same happened for me on Windows.  But I just downloaded 3.181.32 (and all is good)!

![2023-11-23_153503](https://github.com/standardnotes/forum/assets/129994813/d26ceee9-3add-49a1-aad4-3f90f27c1059)

**Comment by theInfiTualEr** [comment]
This happened to me, I uninstalled and re-installed the latest version, and it got fixed,

UNTIL it happened again. I believe I played a game before opening the app, and set the resolution to half of my display resolution, not sure if that would reproduce it again.

**Comment by emptyflask** [comment]
I just got this blank window on linux (nixos) as well, using [version 3.181.23 in nixpkgs](https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/editors/standardnotes).

edit: there's an issue on nixpkgs as well https://github.com/NixOS/nixpkgs/issues/278191
