### ISSUE TITLE
latest-linux.yml - information for a DEB file instead of AppImage

### ISSUE THREAD

**Issue by MorgothSauron** [standardnotes/forum#3441]
**Describe the bug**
I wrote a program few months ago that downloads the latest AppImage using the information in [download/latest-linux.yml](https://github.com/standardnotes/app/releases/latest/download/latest-linux.yml).

It no longer works because `latest-linux.yml` now contains information for a DEB file.

The content of that file changed (DEB file instead of AppImage) and is breaking my automated SN update. Now I have to download the latest AppImage manually.

**To Reproduce**
1. Download the file referenced in `latest-linux.yml`
2. Save that file as an AppImage.
3. Cannot run because it is no longer an AppImage file.

**Expected behavior**
`latest-linux.yml` used to have information for the latest AppImage.

Either revert back to the initial format of `latest-linux.yml` that contained AppImage file info or create a new latest YAML specific for the AppImage (e.g., `latest-linux-appimage.yml`)

**Desktop (please complete the following information):**
 - OS: Linux 6.6
 - Browser N/A
 - Version N/A[e.g. 22]

**Additional context**

**Comment by effieeee** [comment]
I see, though is the AppImage on your device currently unable to pull in updates automatically through the **Updates** menu? (The menu may appear as a dropdown menu on Linux distros)
![image](https://github.com/standardnotes/forum/assets/54989748/e5eb4a68-bdf3-4bca-bf84-7bf683ed4e09)

**Comment by MorgothSauron** [comment]
I never had much luck with the automatic update. Most of the time I was doing a manual download of the AppImage. 

I found that `latest-linux.yml` was providing useful information to automate the update outside of the application. 

My program is/was doing the following on login:
- fetch `latest-linux.yml`
- get the new file name and checksum
- compare the new checksum with the checksum of the AppImage "installed" locally
- download the new AppImage to a temporary folder (if the checksum is different)
- verify the checksum of the downloaded file to control the file integrity
- copy the downloaded AppImage to my "Applications" folder
- change file permissions on the AppImage file to be executable.

It is only recently that I found that `latest-linux.yml` is now providing details for a DEB file. A DEB file, as you can imagine, cannot be run like an AppImage ;)

I didn't find an "alternate" YML file that contains details about the latest AppImage.

**Comment by mscurtescu** [comment]
@effieeee  the automatic update is lately also broken, and the stack trace does make an unexpected reference to a `.deb` file 

```
09:50:05.384 › Checking for update
09:50:06.398 › Found version 3.184.0 (url: standard-notes-3.184.0-linux-amd64.deb)
09:50:06.402 › Downloading update from standard-notes-3.184.0-linux-amd64.deb
09:50:06.403 › Error: TypeError: Cannot read properties of undefined (reading 'info')
    at d.executeDownload (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:390549)
    at d.executeDownload (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:392273)
    at d.doDownloadUpdate (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:380455)
    at d.downloadUpdate (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:388456)
    at d.doCheckForUpdates (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:387809)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hi (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:203619)
updateManager: TypeError: Cannot read properties of undefined (reading 'info')
    at d.executeDownload (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:390549)
    at d.executeDownload (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:392273)
    at d.doDownloadUpdate (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:380455)
    at d.downloadUpdate (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:388456)
    at d.doCheckForUpdates (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:387809)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hi (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:203619) TypeError: Cannot read properties of undefined (reading 'info')
    at d.executeDownload (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:390549)
    at d.executeDownload (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:392273)
    at d.doDownloadUpdate (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:380455)
    at d.downloadUpdate (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:388456)
    at d.doCheckForUpdates (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:387809)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hi (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:203619)
(node:428808) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'info')
    at d.executeDownload (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:390549)
    at d.executeDownload (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:392273)
    at d.doDownloadUpdate (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:380455)
    at d.downloadUpdate (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:388456)
    at d.doCheckForUpdates (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:387809)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async hi (/tmp/.mount_standaX2coah/resources/app.asar/dist/index.js:2:203619)
(node:428808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
```

**Comment by MorgothSauron** [comment]
@effieeee Any chance to get `latest-linux.yml` to reference the AppImage file like before instead of a DEB file ? If not, would it be possible to have a new YML file for the latest AppImage (`latest-linux-appimage.yml`) ? 

Also, it seems I can only update by downloading the AppImage manually. At least I used to be able to automate this process with the old `latest-linux.yml`.

**Comment by MorgothSauron** [comment]
@effieeee Any chance to get this fixed ? I say fixed because `latest-linux.yml` used to contain details about the AppImage.

It was very convenient to have automatic update on multiple computers. There was no need to start the application to update it (although the built-in update seems broken too).

It was also useful because the yml files also contains the checksum. Excellent to automate the verification of the checksum before 'installing' the update.

This is broken for at least a year now.
