### ISSUE TITLE
Latest Flatpak version errors on Fedora Kinoite 39.

### ISSUE THREAD

**Issue by globetrotterdk** [standardnotes/forum#3484]
After install, SN stalls during start process.

When run from the terminal, the following errors appear:

`$ flatpak run org.standardnotes.standardnotes
[3:0206/202217.475101:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Error reading store file Error: ENOENT: no such file or directory, open '/home/user/.var/app/org.standardnotes.standardnotes/config/Standard Notes/user-preferences.json'
    at Object.openSync (node:fs:603:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:2131)
    at Object.readFileSync (node:fs:471:35)
    at Object.readFileSync (node:electron/js2c/asar_bundle:2:9462)
    at T (/app/standardnotes/resources/app.asar/dist/index.js:2:142598)
    at new C (/app/standardnotes/resources/app.asar/dist/index.js:2:144432)
    at new mi (/app/standardnotes/resources/app.asar/dist/index.js:2:204256)
    at /app/standardnotes/resources/app.asar/dist/index.js:2:286249
    at 4053 (/app/standardnotes/resources/app.asar/dist/index.js:2:287351)
    at n (/app/standardnotes/resources/app.asar/dist/index.js:2:832686) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/user/.var/app/org.standardnotes.standardnotes/config/Standard Notes/user-preferences.json'
}
LaunchProcess: failed to execvp:
xdg-settings
[3:0206/202219.123262:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0206/202219.123305:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
20:22:19.192 › Checking for update
extServer: Server started at http://127.0.0.1:45653
20:22:19.220 › Generated new staging user ID: 25a53a27-c161-54cd-9973-36582fb39d4e
[49:0206/202219.223676:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[49:0206/202219.225196:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[49:0206/202219.225298:ERROR:shared_image_factory.cc(926)] CreateSharedImage: could not create backing.
[49:0206/202219.225367:ERROR:shared_image_factory.cc(758)] DestroySharedImage: Could not find shared image mailbox
[49:0206/202219.225496:ERROR:gpu_service_impl.cc(1089)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[3:0206/202219.240409:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=8704
[91:0206/202219.318697:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[91:0206/202219.319952:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[91:0206/202219.320004:ERROR:shared_image_factory.cc(926)] CreateSharedImage: could not create backing.
[91:0206/202219.320056:ERROR:shared_image_factory.cc(758)] DestroySharedImage: Could not find shared image mailbox
[91:0206/202219.320134:ERROR:gpu_service_impl.cc(1089)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[79:0206/202219.322899:ERROR:command_buffer_proxy_impl.cc(127)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[3:0206/202219.345836:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=8704
[104:0206/202219.425671:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[104:0206/202219.426932:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[104:0206/202219.426990:ERROR:shared_image_factory.cc(926)] CreateSharedImage: could not create backing.
[104:0206/202219.427056:ERROR:shared_image_factory.cc(758)] DestroySharedImage: Could not find shared image mailbox
[104:0206/202219.427156:ERROR:gpu_service_impl.cc(1089)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[3:0206/202219.447830:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=8704
20:22:19.841 › Checking for update (already in progress)
20:22:20.771 › Update for version 3.189.1 is not available (latest version: 3.187.3, downgrade is disallowed). `

it looks like this is an electron app. I believe that I have seen something about there being an issue with electron apps on Fedora Silverblue, Kinoite, etc…

**Comment by effieeee** [comment]
Hi @globetrotterdk, yes, Standard Notes is built with Electron, though I should note that the flatpak isn't officially maintained by anyone on the team 🙏 Are you able to check if this happens with the AppImage or the Snap?

**Comment by globetrotterdk** [comment]
This turns out to be an Nvidia driver issue on an atomic/immutable system. I don’t understand why Standard Notes won’t run with the nouveau driver. Dealing with Nvidia appears to be a real pain on Fedora Kinoite, as normal procedure of installing Nvidia drivers from RPM Fusion repo doesn’t work well with immutable system…

**Comment by NTsch** [comment]
I started having the same issue on regular Fedora Workstation a while ago (around the time I switched from X to Wayland). The Snap does work.

**Comment by globetrotterdk** [comment]
Hmm I thought that I more or less understood what was going on, but Fedora 39 KDE spin is giving me problems as well. The Nvidia drivers are installed, but nothing seems to help on a fresh install.
