### ISSUE TITLE
Linux app does not start on wayland (white screen)

### ISSUE THREAD

**Issue by steckes** [standardnotes/forum#3660]
**Describe the bug**
When starting the official AppImage, or the AUR package, the app starts but the window stays white and empty (only the menu bar is showing up). In the terminal I can see the following error:

```bash
Error: TypeError: Cannot read properties of undefined (reading 'info')
[34677:0628/172041.325021:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```

When I search for the error it seems that it is electron related and disabling hardware acceleration seems to fix it. Any idea how I can do that?

**Screenshots**
![Screenshot from 2024-06-28 17-22-49](https://github.com/standardnotes/forum/assets/93521519/6b98e1cd-afed-4d6e-a748-b0a9b09e5800)

**Desktop (please complete the following information):**
 - OS: Linux 6.9.6-arch1-1 / Gnome / Wayland
 - Browser: Desktop App
 - Version: Desktop App Version 3.194.11

**Comment by DaveD54** [comment]
Same issue using Fedora 40 LXDE 
Errors:
link failed but did not provide an info log
12:36:38.175 › Found version 3.194.13 (url: standard-notes-3.194.13-linux-amd64.deb)
12:36:38.183 › Downloading update from standard-notes-3.194.13-linux-amd64.deb
12:36:38.187 › Error: TypeError: Cannot read properties of undefined (reading 'info')
    at d.executeDownload (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:391261)
    at d.executeDownload (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:392985)
    at d.doDownloadUpdate (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:381167)
    at d.downloadUpdate (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:389168)
    at d.doCheckForUpdates (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:388521)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
updateManager: TypeError: Cannot read properties of undefined (reading 'info')
    at d.executeDownload (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:391261)
    at d.executeDownload (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:392985)
    at d.doDownloadUpdate (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:381167)
    at d.downloadUpdate (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:389168)
    at d.doCheckForUpdates (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:388521)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) TypeError: Cannot read properties of undefined (reading 'info')
    at d.executeDownload (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:391261)
    at d.executeDownload (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:392985)
    at d.doDownloadUpdate (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:381167)
    at d.downloadUpdate (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:389168)
    at d.doCheckForUpdates (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:388521)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:4875) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'info')
    at d.executeDownload (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:391261)
    at d.executeDownload (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:392985)
    at d.doDownloadUpdate (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:381167)
    at d.downloadUpdate (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:389168)
    at d.doCheckForUpdates (/tmp/.mount_notesZEMQhH/resources/app.asar/dist/index.js:2:388521)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `standard-notes --trace-warnings ...` to show where the warning was created)
(node:4875) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[4918:0709/123643.049557:ERROR:shared_context_state.cc(98)] Skia shader compilation error

OS: 
Linux DDZenbook 6.9.7-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 27 18:11:45 UTC 2024 x86_64 GNU/Linux

Browser: Firefox 127.0.2
Version: 3.194.7, 3.194.11

**Comment by fnxweb** [comment]
I'm seeing the same thing, near enough;  Fedora 40, Nouveau driver both X11 and Wayland. standard-notes-3.194.11-linux-x86_64.AppImage (but 3.192.10 also failed).  I largely switched to Nouveau from Nvidia's drivers at the same time as upgrading to F40 from F39 so cannot say which may have been the trigger.

**Comment by fnxweb** [comment]
Looks similar to #3610 where it has been found that the following is a possible (temporary) workaround
`rm -fr ~/.config/Standard\ Notes/Cache ~/.config/Standard\ Notes/GPUCache`

**Comment by steckes** [comment]
That did not help with my installation from AUR, but deleting the folders and then installing the AppImage worked :)
Thanks for the hint!
