### ISSUE TITLE
User Registration not working on self hosted Docker

### ISSUE THREAD

**Issue by gammaLx** [standardnotes/forum#960]
Hey,
I followed these instructions (https://docs.standardnotes.org/self-hosting/docker) to install SN on my VPS.
The installation process worked fine and i got no errors. If i open _[myDomain]:3000_ in a browser i get to the page saying "Hi! You're not supposed to be here. You might be looking for the Standard Notes Web App or the main Standard Notes Website."

But i can not register as a new user using any app (iOS, webApp). I always get a generic error message "an error occured …" (the messages pops right after seeing a message "generating keys").

I don't know where to find any usefull information on what could be the problem. Neither `docker logs container_id` gives me any errors.
The only thing i noticed when trying to check the database for any errors is, that i cannot connect from the host to the mysql database. I can get into the db with `docker exec -it id mysql ...`. But trying to connect from the host system via
`mysql -u root -P 3306 -h 127.0.01 -p` or
`mysql -u root -P 3306 -h 172.18.0.2 -p`
gives me `ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)`

Any ideas where i can look for the root of this error?
Any further information i can provide?
thx

EDIT:
Found this issue https://github.com/standardnotes/forum/issues/565
There is no production.log in my application docker. But i did not change the RAILS_ENV flag, which is set to DEVELOPEMENT in the default .env. So i guess the develpoement.log is the place to look for errors.
```# Logfile created on 2020-05-03 07:58:01 +0000 by logger.rb/66358
2020-05-03 07:58:01.216 [WARN ] DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /syncing-server/config/initializers/new_framework_defaults.rb:23) (pid:7)
2020-05-03 07:58:01.780 [DEBUG]  (5.7ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483 (pid:7)
2020-05-03 07:58:01.786 [DEBUG]  (0.3ms)  SELECT GET_LOCK('1196175950333648445', 0) (pid:7)
2020-05-03 07:58:01.810 [DEBUG]  (0.4ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC (pid:7)
2020-05-03 07:58:01.815 [DEBUG] ActiveRecord::InternalMetadata Load (0.4ms)  SELECT  `ar_internal_metadata`.* FROM `ar_internal_metadata` WHERE `ar_internal_metadata`.`key` = 'environment' LIMIT 1 (pid:7)
2020-05-03 07:58:01.822 [DEBUG]  (0.3ms)  BEGIN (pid:7)
2020-05-03 07:58:01.823 [DEBUG]  (0.2ms)  COMMIT (pid:7)
2020-05-03 07:58:01.823 [DEBUG]  (0.3ms)  SELECT RELEASE_LOCK('1196175950333648445') (pid:7)
2020-05-03 07:58:01.829 [DEBUG]  (0.3ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC (pid:7)
2020-05-03 07:58:04.588 [WARN ] DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /syncing-server/config/initializers/new_framework_defaults.rb:23) (pid:1)
2020-05-03 08:38:28.129 [INFO ] Started GET "/" for **FILTERED** at 2020-05-03 08:38:28 +0000 (pid:1)
2020-05-03 08:38:28.144 [INFO ] Processing by ApplicationController#home as HTML (pid:1)
2020-05-03 08:38:28.300 [INFO ] Rendering application/home.html (pid:1)
2020-05-03 08:38:28.302 [INFO ] Rendered application/home.html (1.2ms) (pid:1)
2020-05-03 08:38:28.312 [INFO ] Completed 200 OK in 167ms (Views: 5.2ms) (pid:1)
2020-05-03 08:38:28.414 [INFO ] Started GET "/assets/home.css" for **FILTERED** at 2020-05-03 08:38:28 +0000 (pid:1)```

**Comment by gammaLx** [comment]
I found issue with interesting content https://github.com/standardfile/ruby-server/issues/68
I changed the RAILS_ENV to production. And i tried the ":" instead of "=".
With ":" none of the assigned values where accepted, so switched back to "=" usage.

My production.log shows some problems now.
```# Logfile created on 2020-05-03 11:03:58 +0000 by logger.rb/66358
2020-05-03 11:04:03.337 [INFO ] Started GET "/" for **FILTERED** at 2020-05-03 11:04:03 +0000 (pid:1)
2020-05-03 11:04:03.342 [INFO ] Processing by ApplicationController#home as HTML (pid:1)
2020-05-03 11:04:03.344 [INFO ] Rendering application/home.html (pid:1)
2020-05-03 11:04:03.345 [INFO ] Rendered application/home.html (0.5ms) (pid:1)
2020-05-03 11:04:03.354 [INFO ] Completed 200 OK in 11ms (Views: 1.8ms) (pid:1)
2020-05-03 11:04:03.428 [INFO ] Started GET "/assets/home.css" for **FILTERED** at 2020-05-03 11:04:03 +0000 (pid:1)
2020-05-03 11:04:03.430 [FATAL]  (pid:1)
2020-05-03 11:04:03.430 [FATAL] ActionController::RoutingError (No route matches [GET] "/assets/home.css"): (pid:1)
2020-05-03 11:04:03.430 [FATAL]  (pid:1)
2020-05-03 11:04:03.430 [FATAL] actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
rack (2.2.2) lib/rack/deflater.rb:44:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
secure_headers (6.3.0) lib/secure_headers/middleware.rb:11:in `call'
sentry-raven (3.0.0) lib/raven/integrations/rack.rb:51:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (4.3.3) lib/puma/configuration.rb:228:in `call'
puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
puma (4.3.3) lib/puma/server.rb:472:in `process_client'
puma (4.3.3) lib/puma/server.rb:328:in `block in run'
puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread' (pid:1)
2020-05-03 11:04:05.659 [INFO ] Started GET "/" for **FILTERED** at 2020-05-03 11:04:05 +0000 (pid:1)
2020-05-03 11:04:05.661 [INFO ] Processing by ApplicationController#home as HTML (pid:1)
2020-05-03 11:04:05.661 [INFO ] Rendering application/home.html (pid:1)
2020-05-03 11:04:05.662 [INFO ] Rendered application/home.html (0.1ms) (pid:1)
2020-05-03 11:04:05.662 [INFO ] Completed 200 OK in 2ms (Views: 0.7ms) (pid:1)
2020-05-03 11:04:05.723 [INFO ] Started GET "/assets/home.css" for **FILTERED** at 2020-05-03 11:04:05 +0000 (pid:1)
2020-05-03 11:04:05.724 [FATAL]  (pid:1)
2020-05-03 11:04:05.724 [FATAL] ActionController::RoutingError (No route matches [GET] "/assets/home.css"): (pid:1)
2020-05-03 11:04:05.725 [FATAL]  (pid:1)
2020-05-03 11:04:05.725 [FATAL] actionpack (5.1.7) lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.7) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.7) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
rack (2.2.2) lib/rack/deflater.rb:44:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
secure_headers (6.3.0) lib/secure_headers/middleware.rb:11:in `call'
sentry-raven (3.0.0) lib/raven/integrations/rack.rb:51:in `call'
railties (5.1.7) lib/rails/engine.rb:522:in `call'
puma (4.3.3) lib/puma/configuration.rb:228:in `call'
puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
puma (4.3.3) lib/puma/server.rb:472:in `process_client'
puma (4.3.3) lib/puma/server.rb:328:in `block in run'
puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread' (pid:1)
```

**Comment by gammaLx** [comment]
Further checking:
Loggin into the MySQL DB Container shows
```
mysql> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| standard_notes_db  |
| sys                |
+--------------------+
5 rows in set (0.00 sec)
```
and 
```
mysql> SHOW TABLES;
+-----------------------------+
| Tables_in_standard_notes_db |
+-----------------------------+
| ar_internal_metadata        |
| extension_settings          |
| items                       |
| schema_migrations           |
| users                       |
+-----------------------------+
```
So the DB is created and there is a users table, but the table is empty.

**Comment by johnny243** [comment]
I don't see the `register` request coming up in your logs.

Are you sure that port `3000` is open to the outside world?

**Comment by gammaLx** [comment]
I tried again just 5 minutes ago with ufw disabled. Still the same error. So ufw does not block anything. Is there any iptable magic needed to allow passing of packages to docker containers and vice versa? I guess this would be documented...

In the app i set https://myDomain:3000 as sync server.

**Comment by johnny243** [comment]
> In the app i set https://myDomain:3000 as sync server.

The `syncing-server` does not support `https` out-of-the-box. Please use `http` instead:

> `http`://`your-domain-or-ip`:`3000`

Let me know, thanks!

**Comment by gammaLx** [comment]
Unfortunately that doesn't change anything. If i use the http version i experience the same behaviour.
No log (docker logs app_container, docker logs db_container, production.log in app_container) shows any sign of a connection attempt.
I have nginx running with an automatic http to https redirect, but that includes only port 80 to 443. When i go to http://myDomain:3000 i am not redirected to an https site.

**Comment by johnny243** [comment]
> EDIT: Does it help to give you the actual domain i am using?

Please do so. Look for me on our Slack channel.

> EDIT 2: If i can not use https then i do not understand why i need this:

You'll have to set that yourself. For example, you can put the `syncing-server` behind `nginx`, which will be using HTTPS.
